export const styles = {
    header:{
        width:"100%",
        height:"80px",
        background:"grey",
        display:"flex",
        alignItems:"center",
        paddingLeft:"24px"
    },
    link:{
        textDecoration:"none",
        color:"black",
        fontWeight:"bold",
        fontSize:"24px"
    },
    linkActive:{
        color:"green"
    }
}