import '@/styles/globals.css'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import { styles } from '@/styles/App.styles'
import { Box } from '@mui/material'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
    <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box sx={styles.container}>
      <Header />
      <Box sx={styles.body}>
        <Component {...pageProps} />
      </Box>
      <Footer />
    </Box>
    </>
  )
}
